source :rubygems

gem "sinatra"
gem "dm-core"
gem "dm-sqlite-adapter"
gem "dm-timestamps"
gem "dm-migrations"
gem "dm-serializer"
gem "dm-types"
gem "fitgem"
gem "fitbit"
gem "config"
gem "json"
gem "rest-client"
gem "oauth2"
gem "my_zeo"
gem "httparty"